apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipeline-run
spec:
  workspaces:
    - name: pipeline-ws
      persistentVolumeClaim:
        claimName: my-pvc4
  pipelineRef:
    name: workspace-pipeline-ref

