apiVersion: v1
kind: Pod
metadata:
  name: file-creator-pod
spec:
  volumes:
    - name: storage-volume
      persistentVolumeClaim:
        claimName: my-pvc
  containers:
    - name: file-creator-container
      image: busybox
      command:
        - "/bin/sh"
        - "-c"
        - |
          echo 'Hello, World!' > /data/file1.txt &&
          echo 'This is a test.' > /data/file2.txt &&
          sleep 3600  # Sleep for 1 hour (adjust as needed)
      volumeMounts:
        - mountPath: "/tmp"
          name: storage-volume
